### ISSUE TITLE
Avoid false vulnerability claims based on non-viable attack patterns

### ISSUE THREAD

**Issue by wietse-postfix** [The-Login/SMTP-Smuggling-Website#1]
People are using a tool to detect if an SMTP server may be affected by an email spoofing attack based on SMTP smuggling. 

One such attack involves a sequence  `<CR><LF>.<CR><CR><LF>`, which is not a viable attack pattern. Vulnerability claims based on this pattern are therefore false.

To understand why, recall that an authenticated attacker sends an email message to email service A, that contains a non-standard End-of-DATA in the middle followed by attempted spoofed SMTP commands and message content shown as indented text below.

```
    mail from:<attacker><CR><LF>
    rcpt to:<someone><CR><LF>
    data<CR><LF>
    message content
    non-standard End-of-DATA
        mail from:<spoofed><CR><LF>
        rcpt to:<victim><CR><LF>
        data<CR><LF>            <<== or BDAT if available
        message content
    real End-of-DATA
```

The attacker's goal is that email service A delivers the message to `<someone>` at email service B. That service confuses the non-standard End-of-DATA with a real End-of-DATA, and delivers a message from `<spoofed>` to `<victim>` at service B.

When the attack is successful, the attacker can impersonate any sender in any email domain that is hosted at email service A, and still pass  the sender domain's SPF-based DMARC policy at email service B. 

Coming back to the attack pattern `<CR><LF>.<CR><CR><LF>`, or more generally, `<CR><LF>.whatever`. Note that this has` '.'` at the beginning of a line.

Email service A, as required by RFC 5321, prepends a` '.'` to each email message line that begins with` `'.'``. What it sends to email service B is (attempted spoofed commands and message are shown indented): 

```
    mail from:<attacker><CR><LF>
    rcpt to:<someone><CR><LF>
    data<CR><LF>
    message content
    <CR><LF>..whatever          <<== note the '..' here
        mail from:<spoofed><CR><LF>
        rcpt to:<victim><CR><LF>
        data<CR><LF>            <<== or BDAT if available
        message content
    real End-of-DATA
```

When email service B receives the` <CR><LF>..whatever`, there is no confusion whether this is End-of-DATA. No message is delivered from` <spoofed>` to `<victim>`, instead `<someone>` receives an email message with SMTP commands in the middle.

In summary, this attack pattern does not work. To pacify test tools, I will update Postfix releases, but that is a lower priority.

Meanwhile, I request that tool developers and users avoid vulnerability claims that are based on non-viable attack patterns.

A version of this message was posted to the postfix-users@postfix.org mailing list.

**Comment by The-Login** [comment]
The general issue with SMTP smuggling is the violation of exactly these rules/RFCs. Exchange Online and GMX violated RFC 5322 since they let `<LF>.<CR><LF>` through unfiltered, even though the RFC states _"CR and LF MUST only occur together as CRLF; they MUST NOT appear independently in the body."_ Therefore, it might still be possible that outbound servers letting `<CR><LF>.whatever` sequences through unfiltered exist.  
However, it is unlikely that outbound SMTP servers let `<CR><LF>.whatever` through, based on the previous research. For now, I've removed `<CR><LF>.whatever` test cases from https://github.com/The-Login/SMTP-Smuggling-Tools/blob/main/smtp_smuggling_scanner.py to reduce false positives.  
Also, is this issue supposed to be for this repository or for https://github.com/The-Login/SMTP-Smuggling-Tools?
